services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: skill-test
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    entrypoint: |
      sh -c "cd /app && sh"
    ports:
      - "3000:3000"
    depends_on:
      - skill_test_postgres
    links:
      - skill_test_postgres

  skill_test_postgres:
    image: postgres:17
    shm_size: '512m'
    container_name: skill_test_postgres
    restart: always
    command: postgres -c 'max_connections=191' # add a command to set max_connections to 191 same with prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skill_test
    ports:
      - "5438:5432"




